### ISSUE TITLE
在 combbox 模式下，之前手动添加的值（也就是下拉数据匹配不上的情况）使用 jsxvalues 表单返显不上去

### ISSUE THREAD

**Issue by FE-Girl** [uxcore/uxcore-select2#25]
如题

**Comment by eternalsky** [comment]
感觉提到 select-form-field 那里更好，不过在这里也可以，我先看下原因。

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-select-form-field/commit/b1907a92bd2df3d3030f76a5368261262df84924
